/***************************************************************************
 *                           com_ravnaandtines_ctcjava_NativePublicKey.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_NativePublicKey */

#ifndef _Included_com_ravnaandtines_ctcjava_NativePublicKey
#define _Included_com_ravnaandtines_ctcjava_NativePublicKey
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    getNextPubkey
     * Signature: (J)Lcom/ravnaandtines/ctcjava/NativePublicKey;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_getNextPubkey
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    name_from_key
     * Signature: (J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_name_1from_1key
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    isEnabled
     * Signature: (J)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_isEnabled
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    isRevoked
     * Signature: (J)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_isRevoked
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyExtract
     * Signature: (J)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyExtract
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keySign
     * Signature: (JJB)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keySign
        (JNIEnv *, jobject, jlong, jlong, jbyte);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyAble
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyAble
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyDelete
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyDelete
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keySize
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keySize
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyAlg
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyAlg
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyID
     * Signature: (J)J
     */
    JNIEXPORT jlong JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyID
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyDate
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyDate
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    keyPrint
     * Signature: (J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_keyPrint
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    sec
     * Signature: (J)Lcom/ravnaandtines/ctcjava/NetiveSecretKey;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_sec
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    signature
     * Signature: (J)Lcom/ravnaandtines/ctcjava/Signature;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_signature
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    subkey
     * Signature: (J)Lcom/ravnaandtines/ctcjava/NativePublicKey;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_subkey
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    username
     * Signature: (J)Lcom/ravnaandtines/ctcjava/NativePublicKey;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_username
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_NativePublicKey
     * Method:    check
     * Signature: (JJJ)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_NativePublicKey_check
        (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
