/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_LicenceDialog */

#ifndef _Included_com_ravnaandtines_ctcjava_LicenceDialog
#define _Included_com_ravnaandtines_ctcjava_LicenceDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ravnaandtines_ctcjava_LicenceDialog
 * Method:    getGPL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_LicenceDialog_getGPL
  (JNIEnv *, jclass);

/*
 * Class:     com_ravnaandtines_ctcjava_LicenceDialog
 * Method:    getIDEA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_LicenceDialog_getIDEA
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
