/***************************************************************************
 *                           com_ravnaandtines_ctcjava_DecryptionContext.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_DecryptionContext */

#ifndef _Included_com_ravnaandtines_ctcjava_DecryptionContext
#define _Included_com_ravnaandtines_ctcjava_DecryptionContext
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_DecryptionContext
     * Method:    getFirstPubkey
     * Signature: (J)Lcom/ravnaandtines/ctcjava/NativePublicKey;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_DecryptionContext_getFirstPubkey
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_DecryptionContext
     * Method:    getFirstSeckey
     * Signature: (J)Lcom/ravnaandtines/ctcjava/NativeSecretKey;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_DecryptionContext_getFirstSeckey
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
