/***************************************************************************
 *                           com_ravnaandtines_ctcjava_CTCJLicenceDialog.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_CTCJLicenceDialog */

#ifndef _Included_com_ravnaandtines_ctcjava_CTCJLicenceDialog
#define _Included_com_ravnaandtines_ctcjava_CTCJLicenceDialog
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_CTCJLicenceDialog
     * Method:    getGPL
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_CTCJLicenceDialog_getGPL
        (JNIEnv *, jobject);

    /*
     * Class:     com_ravnaandtines_ctcjava_CTCJLicenceDialog
     * Method:    getIDEA
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_CTCJLicenceDialog_getIDEA
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
