/***************************************************************************
 *                           com_ravnaandtines_ctcjava_CJencryptInsts.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_CJencryptInsts */

#ifndef _Included_com_ravnaandtines_ctcjava_CJencryptInsts
#define _Included_com_ravnaandtines_ctcjava_CJencryptInsts
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_CJencryptInsts
     * Method:    reset
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_CJencryptInsts_reset
        (JNIEnv *, jclass);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJencryptInsts
     * Method:    setFile
     * Signature: (Ljava/lang/String;C)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_CJencryptInsts_setFile
        (JNIEnv *, jclass, jstring, jchar);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJencryptInsts
     * Method:    setVersion
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_CJencryptInsts_setVersion
        (JNIEnv *, jclass, jint);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJencryptInsts
     * Method:    addRecipient
     * Signature: (J)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_CJencryptInsts_addRecipient
        (JNIEnv *, jclass, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJencryptInsts
     * Method:    setSignatory
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_CJencryptInsts_setSignatory
        (JNIEnv *, jclass, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJencryptInsts
     * Method:    setAlgs
     * Signature: (IIIII)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_CJencryptInsts_setAlgs
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
