/***************************************************************************
 *                           com_ravnaandtines_ctcjava_CTC.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_CTC */

#ifndef _Included_com_ravnaandtines_ctcjava_CTC
#define _Included_com_ravnaandtines_ctcjava_CTC
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_CTC
     * Method:    registerJVM
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_CTC_registerJVM
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
