/***************************************************************************
 *                           com_ravnaandtines_ctcjava_Username.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_Username */

#ifndef _Included_com_ravnaandtines_ctcjava_Username
#define _Included_com_ravnaandtines_ctcjava_Username
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_Username
     * Method:    getNextUsername
     * Signature: (J)Lcom/ravnaandtines/ctcjava/Username;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_Username_getNextUsername
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_Username
     * Method:    signature
     * Signature: (J)Lcom/ravnaandtines/ctcjava/Signature;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_Username_signature
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_Username
     * Method:    name
     * Signature: (J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_ravnaandtines_ctcjava_Username_name
        (JNIEnv *, jobject, jlong);

    /*
     * Class:     com_ravnaandtines_ctcjava_Username
     * Method:    keySign
     * Signature: (JJJB)V
     */
    JNIEXPORT void JNICALL Java_com_ravnaandtines_ctcjava_Username_keySign
        (JNIEnv *, jobject, jlong, jlong, jlong, jbyte);

#ifdef __cplusplus
}
#endif
#endif
