/***************************************************************************
 *                           com_ravnaandtines_ctcjava_CJFilesPanel.h  -  description
 *                              -------------------
 *     copyright            : (C) 1998 by Mr. Tines
 *     email                : tines@ravnaandtines.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ravnaandtines_ctcjava_CJFilesPanel */

#ifndef _Included_com_ravnaandtines_ctcjava_CJFilesPanel
#define _Included_com_ravnaandtines_ctcjava_CJFilesPanel
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_ravnaandtines_ctcjava_CJFilesPanel
     * Method:    readPubring
     * Signature: (Ljava/lang/String;)Lcom/ravnaandtines/ctcjava/CJdecodeContext;
     */
    JNIEXPORT jobject JNICALL Java_com_ravnaandtines_ctcjava_CJFilesPanel_readPubring
        (JNIEnv *, jobject, jstring);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJFilesPanel
     * Method:    readSecring
     * Signature: (Ljava/lang/String;)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_CJFilesPanel_readSecring
        (JNIEnv *, jobject, jstring);

    /*
     * Class:     com_ravnaandtines_ctcjava_CJFilesPanel
     * Method:    clearKeyrings
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_com_ravnaandtines_ctcjava_CJFilesPanel_clearKeyrings
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
